name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Get version
        id: get-version
        run: |
          version=$(cat version.json | jq --raw-output .version)

          echo "releaseVersion=$version" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          name: v${{ steps.get-version.outputs.releaseVersion }}
          tag_name: v${{ steps.get-version.outputs.releaseVersion }}
          files: |
            ./dist/ga-analytics.min.js
            ./dist/ga-analytics-escapedForBackticks.txt
            ./dist/plausible-analytics.min.js
            ./dist/plausible-analytics-escapedForBackticks.txt
